### PR TITLE
[#4] Add return types to methods inherited from PHP ArrayAccess

### LINKED ISSUE #4: Inheritance of ArrayAccess broken in PHP >=8.1
PHP `8.1` [added return types to its built-in interfaces](https://php.watch/versions/8.1/internal-method-return-types), and requires those implementing them to also define them.

They are currently missing from the two classes in this library, `Map` and `CMap`, which implement PHP's `\ArrayAccess` interface, leading to errors like:

```
PHP Fatal error:  During inheritance of ArrayAccess: Return type of transit\Map::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /foo/vendor/honzabrecka/transit-php/src/transit/Map.php:66
```

This is easily fixable by adding the 4 return types to the four methods in each of the two classes. I will submit a pull request to fix this.

### PR DESCRIPTION
**Pull request by vincent-dm**
Fixes #4.

### CODE REVIEW

**Comment by honzabrecka** [comment]
Thanks, published as 0.8.5.

**Comment by vincent-dm** [comment]
Thanks! Have you published it to Packagist (Composer) too? I can't see it there yet, but maybe there is some delay in that process?

**Comment by honzabrecka** [comment]
I thought it's automatic... it was not. :) https://packagist.org/packages/honzabrecka/transit-php#0.8.5

**Comment by vincent-dm** [comment]
Great, thanks!

**Pull request merged**
